version: '2'

services:
    db:
        image: mysql/mysql-server:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: Movies
            MYSQL_USER: movies
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
 #       volumes:
 #           - dbdata:/var/lib/mysql
 #           - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
 #           - C:\Users\scamara\Documents\Movies\my.cnf:/etc/alternatives/my.cnf
    moviesbackend:
        depends_on:
            - db
        image: ${DOCKER_REGISTRY-}moviesbackend       
        build:
            context: .
            dockerfile: MoviesBackend/Dockerfile
#volumes:
#    dbdata: